on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment on PR reminder
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for updating the website! :tada:

            Did you happend to add your new publication?
            
            If yes do not forget to,

            - Let our librarian :books: know (form:)
            - Contact, 
